### ISSUE TITLE
errore

### ISSUE THREAD

**Issue by 23bca272** [vtcbca/internal-exam-23bca272#2]

**Comment by 23bca274** [comment]
Do as following : 

1. import sqlite3 and csv
2. connect to the sqlite3 and create cursor
3. write creating table query in cursor.execute() and then execute that query 
4. create trigger to check total match is not zero
5. insert records by using cursor.execute() then fetchall records and print
6. export the data to a csv file "w"
7. read the file using a CSV reader and calculate the winning percentage and print it 

I hope these steps will help you out to solve the error

**Comment by 23bca272** [comment]
> Do as following :
> 
> 1. import sqlite3 and csv
> 2. connect to the sqlite3 and create cursor
> 3. write creating table query in cursor.execute() and then execute that query
> 4. create trigger to check total match is not zero
> 5. insert records by using cursor.execute() then fetchall records and print
> 6. export the data to a csv file "w"
> 7. read the file using a CSV reader and calculate the winning percentage and print it
> 
> I hope these steps will help you out to solve the error

Thank you for your suggestion . That was helped me a lot !

**Comment by 23bca272** [comment]
T

**Comment by 23bca272** [comment]
> Do as following :
> 
> 1. import sqlite3 and csv
> 2. connect to the sqlite3 and create cursor
> 3. write creating table query in cursor.execute() and then execute that query
> 4. create trigger to check total match is not zero
> 5. insert records by using cursor.execute() then fetchall records and print
> 6. export the data to a csv file "w"
> 7. read the file using a CSV reader and calculate the winning percentage and print it
> 
> I hope these steps will help you out to solve the error

Thank you for your suggestion. That was helped me a lot.
